add: Made a C program for generating aroma-config and updater-script, added ics theme and removed docs/

diff --git a/src/aroma_installer/META-INF/com/google/android/updater-script b/src/aroma_installer/META-INF/com/google/android/updater-script
--- a/src/aroma_installer/META-INF/com/google/android/updater-script
+++ b/src/aroma_installer/META-INF/com/google/android/updater-script
@@ -1,97 +1,91 @@
-# to be handled by a bash script!
+# import the functions and variables.
+source "${INSTALLER}/scripts/util_functions.sh"
 
-# Oh, she's sweet but a psycho
-# A little bit psycho
-# At night, she's screamin'
-# "I'm-ma-ma-ma out my mind"
-# Oh, she's hot but a psycho
-# So left but she's right, though
-# At night, she's screamin'
-# "I'm-ma-ma-ma out my mind"
-# 
-# She'll make you curse, but she a blessin'
-# She'll rip your shirt within a second
-# You'll be coming back, back for seconds
-# With your plate, you just can't help it
-# 
-# No, no, you'll play along
-# Let her lead you on
-# You'll be saying, "No, no"
-# Then saying, "Yes, yes, yes"
-# 'Cause she messin' with your head
-# 
-# Oh, she's sweet but a psycho
-# A little bit psycho
-# At night, she's screamin'
-# "I'm-ma-ma-ma out my mind"
-# Oh, she's hot but a psycho
-# So left but she's right, though
-# At night, she's screamin'
-# "I'm-ma-ma-ma out my mind"
-# 
-# "Grab a cop gun" kinda crazy
-# She's poison but tasty
-# Yeah, people say, "Run, don't walk away"
-# 'Cause she's sweet but a psycho
-# A little bit psycho
-# At night, she's screamin'
-# "I'm-ma-ma-ma out my mind"
-# 
-# See, someone said, "Don't drink her potions
-# She'll kiss your neck with no emotion
-# When she's mean, you know you love it
-# 'Cause she tastes so sweet, don't sugarcoat it"
-# 
-# No, no, you'll play along
-# Let her lead you on
-# You'll be saying, "No (no, no, no), no (no)"
-# Then saying, "Yes, yes, yes"
-# 'Cause she messin' with your head (hey)
-# 
-# Oh, she's sweet but a psycho
-# A little bit psycho
-# At night, she's screamin'
-# "I'm-ma-ma-ma out my mind"
-# Oh, she's hot but a psycho
-# So left but she's right, though
-# At night, she's screamin'
-# "I'm-ma-ma-ma out my mind"
-# 
-# "Grab a cop gun" kinda crazy
-# She's poison but tasty
-# Yeah, people say, "Run, don't walk away"
-# 'Cause she's sweet but a psycho
-# A little bit psycho
-# At night, she's screamin'
-# "I'm-ma-ma-ma out my mind"
-# 
-# You're just like me, you're out your mind
-# I know it's strange, we're both the crazy kind
-# You're tellin' me that I'm insane
-# Boy, don't pretend that you don't love the pain
-# 
-# Oh, she's sweet but a psycho
-# A little bit psycho
-# At night, she's screamin'
-# "I'm-ma-ma-ma out my mind"
-# Oh, she's hot but a psycho
-# So left but she's right, though
-# At night, she's screamin'
-# "I'm-ma-ma-ma out my mind"
-# 
-# "Grab a cop gun" kinda crazy
-# She's poison but tasty
-# Yeah, people say, "Run, don't walk away"
-# 'Cause she's sweet but a psycho
-# A little bit psycho
-# At night, she's screamin'
-# "I'm-ma-ma-ma out my mind"
+# put your flashable images list here:
+flashables="/dev/block/by-name/system -> horizon/system.img -> raw "
 
-# setup the script environment and execute it
-export INSTALLER="$TMPDIR/install"
-mkdir -p "$INSTALLER" || exit 1
-for file in "scripts/installer.sh" scripts/util_functions.sh; do
-    unzip -o "$3" "$file" -d "${INSTALLER}/"; || exit 1
+# device codename / model detection, better put your device's codename / model for checking it
+# the "|" works as a separator.
+supportedDeviceCodenameList="surya|karna"
+
+# now the real functions start!
+consolePrint "########################################################################"
+consolePrint "   _  _     _   _            _                _   ___  __ "
+consolePrint " _| || |_  | | | | ___  _ __(_)_______  _ __ | | | \ \/ / "
+consolePrint "|_  ..  _| | |_| |/ _ \| '__| |_  / _ \| '_ \| | | |\  /  "
+consolePrint "|_      _| |  _  | (_) | |  | |/ / (_) | | | | |_| |/  \  "
+consolePrint "  |_||_|   |_| |_|\___/|_|  |_/___\___/|_| |_|\___//_/\_\ "
+consolePrint "                                                         "
+consolePrint "########################################################################"
+getprop ro.product.system.device | grep -qE "${supportedDeviceCodenameList}" || abort "This build is made for ${supportedDeviceCodenameList} not for your device."
+unmountPartitions && consolePrint "Successfully unmounted partitions!" || abort "Failed to unmount partitions, please try again after a reboot."
+consolePrint "Horizon - Birds for Galaxy A30 | Built by Luna"
+[ "$(acpi)" -le "35" ] && abort "Please atleast charge your device to 40% to continue the installation"
+set -- $flashables
+while [ "$1" ]; do
+    image="$1"
+    shift
+    delimiter="$1"
+    shift
+    target="$1"
+    shift
+    shift
+    imageType="$1"
+    shift
+    if [ "$delimiter" = "->" ]; then
+        consolePrint "Patching $(basename "${image}" .img) image unconditionally..."
+        installImages "$image" "$target" "${imageType}"
+    else
+        abort "Error: Expected '->' but got '$delimiter'"
+    fi
 done
-
-exec sh "$INSTALLER/scripts/installer.sh" "/dev/null" "$2" "$3"
+consolePrint "Handling aroma actions.."
+if [ "$(getAromaProp "item.1.0" "/tmp/checkbox0.prop")" == "1" ]; then
+    unzip -o "${ZIPFILE}" "IndexOneSourceOne:" "${INSTALLER}/"
+    mv "${INSTALLER}/IndexOneSourceOne:" "IndexOneExtractOne:"
+fi
+if [ "$(getAromaProp "item.1.1" "/tmp/checkbox0.prop")" == "1" ]; then
+    unzip -o "${ZIPFILE}" "IndexOneSourceTwo:" "${INSTALLER}/"
+    mv "${INSTALLER}/IndexOneSourceTwo:" "IndexOneExtractTwo:"
+fi
+if [ "$(getAromaProp "item.1.0" "/tmp/checkbox1.prop")" == "1" ]; then
+    unzip -o "${ZIPFILE}" "IndexTwoSourceOne:" "${INSTALLER}/"
+    mv "${INSTALLER}/IndexTwoSourceOne:" "IndexTwoExtractOne:"
+fi
+if [ "$(getAromaProp "item.1.1" "/tmp/checkbox1.prop")" == "1" ]; then
+    unzip -o "${ZIPFILE}" "IndexTwoSourceTwo:" "${INSTALLER}/"
+    mv "${INSTALLER}/IndexTwoSourceTwo:" "IndexTwoExtractTwo:"
+fi
+if [ "$(getAromaProp "item.1.0" "/tmp/checkbox2.prop")" == "1" ]; then
+    unzip -o "${ZIPFILE}" "IndexThreeSourceOne:" "${INSTALLER}/"
+    mv "${INSTALLER}/IndexThreeSourceOne:" "IndexThreeExtractOne:"
+fi
+if [ "$(getAromaProp "item.1.1" "/tmp/checkbox2.prop")" == "1" ]; then
+    unzip -o "${ZIPFILE}" "IndexThreeSourceTwo:" "${INSTALLER}/"
+    mv "${INSTALLER}/IndexThreeSourceTwo:" "IndexThreeExtractTwo:"
+fi
+if [ "$(getAromaProp "item.1.0" "/tmp/checkbox3.prop")" == "1" ]; then
+    unzip -o "${ZIPFILE}" "IndexFourSourceOne:" "${INSTALLER}/"
+    mv "${INSTALLER}/IndexFourSourceOne:" "IndexFourExtractOne:"
+fi
+if [ "$(getAromaProp "item.1.1" "/tmp/checkbox3.prop")" == "1" ]; then
+    unzip -o "${ZIPFILE}" "IndexFourSourceTwo:" "${INSTALLER}/"
+    mv "${INSTALLER}/IndexFourSourceTwo:" "IndexFourExtractTwo:"
+fi
+consolePrint "                                              "
+consolePrint "              ******       ******"
+consolePrint "            **********   **********"
+consolePrint "          ************* *************"
+consolePrint "         *****************************"
+consolePrint "         *****************************"
+consolePrint "         *****************************"
+consolePrint "          ***************************"
+consolePrint "            ***********************"
+consolePrint "              *******************"
+consolePrint "                ***************"
+consolePrint "                  ***********"
+consolePrint "                    *******"
+consolePrint "                      ***"
+consolePrint "                       *"
+consolePrint "Thank you dear user for considering my project"
+consolePrint "let us know your thoughts on our official chat."
